// Say-once store: markdown policies under .hos/memory/.

import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { FRICTION_DIR, MEMORY_DIR, MEMORY_INDEX, POLICY_DIR } from "./paths.mjs";
import { slugify, today, tokenize, writeFileAtomic } from "./util.mjs";
import * as fm from "./frontmatter.mjs";

// tokenize lives in util.mjs (shared with task matching); re-exported so callers
// and tests that read it from the memory store keep working.
export { tokenize };

function ensureDirs() {
    for (const dir of [MEMORY_DIR, POLICY_DIR, FRICTION_DIR]) {
        mkdirSync(dir, { recursive: true });
    }
}

function readDir(dir) {
    return existsSync(dir) ? readdirSync(dir).filter((f) => f.endsWith(".md") && f !== "README.md") : [];
}

// Load every policy as { id, title, scope, triggers, status, body, file }.
export function loadPolicies() {
    return readDir(POLICY_DIR).map((file) => {
        const parsed = fm.parse(readFileSync(join(POLICY_DIR, file), "utf8"));
        return {
            file,
            id: parsed.data.id || file.replace(/\.md$/, ""),
            ...parsed.data,
            triggers: parsed.data.triggers || [],
            body: parsed.body
        };
    });
}

// Score policies against free text by trigger and scope-keyword overlap; return
// the matches sorted strongest-first. This is what every persona calls before
// acting so settled rules are pre-applied.
export function search(text, { scope = null, limit = 20 } = {}) {
    const words = new Set(tokenize(text));
    const policies = loadPolicies();
    const scoped = scope
        ? policies.filter((p) => !p.scope || scope.startsWith(p.scope) || p.scope.startsWith(scope))
        : policies;

    return scoped
        .filter((p) => (p.status || "active") === "active")
        .map((p) => ({
            policy: p,
            score: [...(p.triggers || []), ...tokenize(p.title || "")]
                .reduce((s, t) => s + (words.has(t.toLowerCase()) ? 1 : 0), 0)
        }))
        .filter((m) => m.score > 0)
        .sort((a, b) => b.score - a.score)
        .slice(0, limit)
        .map((m) => m.policy);
}

// Render matched policies as the "Active policies" block injected into composed
// prompts. Shared by `hos compose` and the benchmark so both exercise the exact
// text an executing agent sees. Returns "" when nothing matched.
export function renderPolicyBlock(policies) {
    if (!policies.length) {
        return "";
    }
    return "# Active policies (say-once memory)\n\n"
        + policies.map((p) => `- **${p.title}** - ${p.body}`).join("\n");
}

// Add (or update) a durable policy. The slug of the title is the id and the
// filename, so re-stating the same rule updates one file instead of spawning a
// numbered duplicate. Returns the file path.
export function addPolicy({ title, body, scope = "", triggers = [], source = "user" }) {
    ensureDirs();
    const id = slugify(title);
    const file = join(POLICY_DIR, `${id}.md`);
    const data = {
        id, title, scope, status: "active", source,
        triggers: triggers.length ? triggers : tokenize(title).slice(0, 8),
        created: today()
    };
    writeFileSync(file, fm.serialize(data, body || title));
    rebuildIndex();
    return file;
}

// Append a raw friction note (slug-named) for later graduation into a policy.
export function addFriction({ title, body }) {
    ensureDirs();
    const id = slugify(title);
    const file = join(FRICTION_DIR, `${id}.md`);
    writeFileSync(file, fm.serialize({ id, title, created: today() }, body || title));
    return file;
}

// Regenerate index.md as the human-readable map of all policies.
export function rebuildIndex() {
    ensureDirs();
    const rows = loadPolicies()
        .sort((a, b) => String(a.id).localeCompare(String(b.id)))
        .map((p) => `| \`${p.id}\` | ${p.title} | \`${p.scope || "-"}\` | ${p.status || "active"} | ${p.source || "-"} |`);
    const out = [
        "# Memory Index",
        "",
        "Every active policy in this store. The id is the filename slug (merge-safe,",
        "no counters). Generated by `hos memory index` -- do not edit by hand.",
        "See `.hos/doc/protocol/memory.md`.",
        "",
        "| ID | Title | Scope | Status | Source |",
        "| -- | ----- | ----- | ------ | ------ |",
        ...(rows.length ? rows : ["| - | _none yet_ | - | - | - |"]),
        ""
    ].join("\n");
    writeFileAtomic(MEMORY_INDEX, out);
    return MEMORY_INDEX;
}
